LogbookFilter: do not fail filter chain on I/O error from resp flushing
Ignore various I/O errors like "Broken Pipe" from response.flushBuffer()
which is done before HTTP log writing as these might occur in real world
situations. We do not want to them to fail the whole filter chain.

E.g. in case of async, this should minimize stuff like
"java.io.IOException: Broken pipe" bubbling up to
AsynxContext.onComplete() call which makes some servlet containers
complain about it quite loudly about it. E.g. on Tomcat:

WARN org.apache.catalina.core.AsyncContextImp: onComplete() call failed for listener of type [org.apache.catalina.core.AsyncListenerWrapper]
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
...
  at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
  at org.zalando.logbook.servlet.LocalResponse.flushBuffer(LocalResponse.java:215)
  at org.zalando.logbook.servlet.LogbookFilter.write(LogbookFilter.java:86)
  at org.zalando.logbook.servlet.LogbookFilter.lambda$doFilter$0(LogbookFilter.java:71)
  at org.zalando.logbook.servlet.LogbookAsyncListener.onComplete(LogbookAsyncListener.java:17)
  at org.apache.catalina.core.AsyncListenerWrapper.fireOnComplete(AsyncListenerWrapper.java:39)
...